// FAKE DATA
export const books = [
  {
    id: 1,
    title: "The Silmarillion",
    url: "https://d29xot63vimef3.cloudfront.net/image/jrr-tolkien-books/7-8.jpg",
    originalPrice: 49.95,
    salePrice: null,
    rating: 5,
  },
  {
    id: 2,
    title: "The Hobbit",
    url: "https://m.media-amazon.com/images/I/71UZKQ3-wCL._SY385_.jpg",
    originalPrice: 39.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "The Fellowship Of The Ring",
    url: "https://d29xot63vimef3.cloudfront.net/image/jrr-tolkien-books/146-5.jpg",
    originalPrice: 29.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "The Return Of The Shadow",
    url: "https://books.google.com/books/publisher/content?id=8roxEAAAQBAJ&pg=PA1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2D0BFtT0bdQh8MOgcvx03c-vdV1Q&w=1280",
    originalPrice: 44.00,
    salePrice: 19.00,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The Fall Of Gondolin",
    url: "https://books.google.com/books/publisher/content?id=bPJUDwAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U0qvu51fRC2kI6AoDatIj76Hgoltw&w=1280",
    originalPrice: 29.43,
    salePrice: 19.12,
    rating: 4,
  },
  {
    id: 6,
    title: "The Adventures Of Tom Bombadil",
    url: "https://books.google.com/books/publisher/content?id=N_zzEAAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2WJzEhacc2biRxx7J4YJRzeN_FSA&w=1280",
    originalPrice: 19.12,
    salePrice: 15.99,
    rating: 4.5,
  },
  {
    id: 7,
    title: "Beren and Lúthien",
    url: "https://books.google.com/books/publisher/content?id=r4pODQAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U225A5QYCr9TYzPX1UutMtoEoWDmg&w=1280",
    originalPrice: 20.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 8,
    title: "The Two Towers",
    url: "https://books.google.com/books/content?id=12e8PJ2T7sQC&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U0ZGpeqk2ed84chNpEKaNMLirIacg&w=1280",
    originalPrice: 25.99,
    salePrice: 19.99,
    rating: 3.5,
  },
  {
    id: 9,
    title: "Tree and Leaf: Including Mythopoeia",
    url: "https://books.google.com/books/publisher/content?id=pxY_EAAAQBAJ&pg=PA2&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U20kIc5TbW8LkukEdkoQZJ5TEuxPQ&w=1280",
    originalPrice: 22.45,
    salePrice: 15.99,
    rating: 4.5,
  },
  {
    id: 10,
    title: "The Fall of Númenor",
    url: "https://books.google.com/books/publisher/content?id=owZwEAAAQBAJ&pg=PA1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U3qbHYs9_CEtd6MN4Haqxy4Evkk2w&w=1280",
    originalPrice: 39.48,
    salePrice: 29.99,
    rating: 3.5,
  },
  {
    id: 11,
    title: "Roverandom",
    url: "https://books.google.com/books/publisher/content?id=2TEPAAAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U0noP7gFRFecrqgp07s2Y1eQV0RMg&w=1280",
    originalPrice: 38.94,
    salePrice: 29.99,
    rating: 4.5,
  },
  {
    id: 12,
    title: "Farmer Giles of Ham",
    url: "https://books.google.com/books/publisher/content?id=IxD9EAAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U0MpRFTpxoB1ycOAmhp7ilqFkKGuw&w=1280",
    originalPrice: 38.99,
    salePrice: 29.99,
    rating: 4,
  },
];
